version: "3.1"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2345:80"
    volumes:
      - ./src:/var/www/html

  db:
    image: "mariadb"
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: docker_exo
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
